title: "Community Rules for Archival Description (RAD)"
description: "An archivist led site for applying and revising RAD"
url: "https://gphippard.github.io"
baseurl: "/Rules_Archival_Description"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: false

markdown: kramdown
highlighter: rouge
