title: "Community RAD"
description: "An archivist led site for applying and revising RAD"
url: "https://gphippard.github.io"
baseurl: "/Rules_Archival_Description"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-relative-links

collections:
  rad:
    output: true
    permalink: /RAD/:path/


defaults:
  # RAD collection pages
  - scope:
      path: ""
      type: rad
    values:
      layout: single

  # All pages
  - scope:
      path: ""
    values:
      sidebar:
        nav: "main-sidebar"
      sidebar_position: left
      comments: true

relative_links:
  enabled: true
  collections: false

navigation: true
search: true
search_full_content: true
atom_feed: 
  hide: true
recent_posts:
  hide: true

# Giscus Comments
comments:
  provider: "giscus"
  enabled: true
  force: true
  giscus:
    repo: "gphippard/Rules_Archival_Description"
    repo_id: "R_kgDONMFzow"
    category: "General"
    category_id: "DIC_kwDONMFzo84C4p79"
    discussion_term: "og:title"
    strict: 0
    reactions_enabled: 1
    emit_metadata: 0
    input_position: "bottom"
    theme: "preferred_color_scheme"
    lang: "en"
    lazy: true

markdown: kramdown
highlighter: rouge
